title: Uli Fahrer
url: http://www.uli-fahrer.de
permalink: /blog/:year/:month/:day/:title
baseurl: ""
description: "Uli Fahrer: DevSecOps Engineer"

kramdown:
  input: GFM
  syntax_highlighter: rouge

github_username: Tooa
